version: '3'
services:
  server:
    env_file: './server/.env'
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: 'settar/crud-server-image'
    ports:
      - '5000:5000'
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: 'settar/crud-client-image'
    ports:
      - '3000:3000'
    links:
      - 'server:localhost'
